version: "3.5"

services:
  personal-website:
    image: personal-website
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    container_name: personal-website_default
    volumes:
      - ..:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
